GOOGLE = "google"
GOOGLE_SELENIUM = "google_selenium"
GOOGLE_API = "google_api"
BING = "bing"
BING_API = "bing_api"
BING_SELENIUM = "bing_selenium"

QUERY = "query"
TYPE = "type"
TOTAL = "total"
UNHANDLED = "unhandled"
MAORI = "maori"
ITEMS = "items"
URL = "url"
URL_HASH = "url_hash"
